version: '3'

networks: 
    network:

services:
    traefik:
        image: traefik
        container_name: reverse-proxy
        command:
            - --api
            - --providers.docker
            - --providers.docker.exposedbydefault=false
        ports:
            - "80:80"
            - "8080:8080"
        expose:
            - 8080
        labels:
            traefik.enable: true
            traefik.http.routers.subdomains.rule: HostRegexp(`easytentacles.fun`,`{subhost:[a-z]+}.easytentacles.fun`)
            traefik.http.routers.subdomains.middlewares: auth
            traefik.http.routers.subdomains.service: api@internal
            traefik.http.middlewares.auth.basicauth.users: curran:{SHA}jsSt4GSwtIUuiJ4H84bT35SSC6I=
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
            - ./traefik.yml:/traefik.yml
        restart: "always"
        networks: 
            - network