version: '3'

services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        user: curran
        uid: 1000
    container_name: web-app
    ports:
      - 8001:8001
    image: web-app
    volumes: 
      - ./src:/var/www
    environment: 
      VIRTUAL_HOST: curran.test

  nginx-proxy:
    image: nginx:1.17.10
    container_name: nginx-reverse
    depends_on: 
      - web-app
    volumes: 
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80