version: '3'

services:
  web-app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        user: curran
        uid: 1000
    container_name: web-app
    ports:
      - "8000:8000"
    image: web-app
    volumes: 
      - ./src:/var/www